language: rust
sudo: false
cache:
  - cargo

rust:
  - stable

branches:
  only:
  - master

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.2.3" mdbook)
  - cargo install-update -a

script:
  - cd rustwasmbook-ko && mdbook build && mdbook test && cd book && touch .nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: rustwasmbook-ko/book
  on:
    branch: master